name: Check
on:
  push:
    branches: [ main, tsc-check ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint:check

      - name: Create dummy config file
        run: |
          echo '{ "token": "", "discordGuild": "", "guildWarsChannel": "", "guildWarsToken": "", "guildWarsGuildId": "", "guildWarsAccounts": [] }' \
              > src/config.json

      - name: Check compilation
        run: npm run build


