name: Check
on:
  push:
    branches: [ github-action ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint:check
